(()=>{
const GAME_NAMES={vocabulary:'Vocabulary Match',hangman:'Word Challenge',present_continuous:'Present Continuous',quantifiers:'Quantifiers',comparatives:'Comparatives',race:'Corrida Maluca'};
const cfg=window.TUG_SUPABASE_CONFIG||{};
const sb=(cfg.url&&cfg.key&&window.supabase&&window.supabase.createClient)?window.supabase.createClient(cfg.url,cfg.key):null;
function deviceId(){let v=localStorage.getItem('egh7SoloDevice');if(!v){v='solo7_'+crypto.getRandomValues(new Uint32Array(4)).join('_');localStorage.setItem('egh7SoloDevice',v)}return v}
function profile(){try{return JSON.parse(localStorage.getItem('egh7SoloPlayer')||'null')}catch(e){return null}}
function esc(s){return String(s==null?'':s).replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]))}
function ensureStyles(){if(document.getElementById('soloRankStyle'))return;const s=document.createElement('style');s.id='soloRankStyle';s.textContent='.soloRankOv{position:fixed;inset:0;z-index:20000;display:flex;align-items:center;justify-content:center;padding:12px;background:#05071df2;backdrop-filter:blur(7px);color:#fff;font-family:Arial,sans-serif}.soloRankCard{width:min(94vw,560px);max-height:94dvh;overflow:auto;border-radius:24px;padding:18px;background:linear-gradient(155deg,#12275b,#351361 58%,#075985);border:2px solid #ffe66d99;box-shadow:0 24px 70px #0008;text-align:center}.soloRankCard h2{margin:0 0 4px;color:#ffe66d;font-size:28px}.soloRankMe{margin:8px 0 12px;font-weight:1000;color:#dffcff}.soloRankList{display:grid;gap:6px}.soloRankRow{display:grid;grid-template-columns:42px 1fr auto;gap:7px;align-items:center;padding:9px 10px;border-radius:12px;background:#ffffffed;color:#172033;text-align:left;font-weight:900}.soloRankRow.me{outline:3px solid #ffe66d;background:#fff7c2}.soloRankRow small{display:block;color:#64748b;font-size:10px}.soloRankBtns{display:grid;grid-template-columns:1fr 1fr;gap:8px;margin-top:12px}.soloRankBtns button,.soloRankBtns a{border:0;border-radius:13px;padding:12px;text-decoration:none;font-weight:1000;font-size:14px;cursor:pointer}.soloAgain{background:#4ade80;color:#052e16}.soloHub{background:#60a5fa;color:#fff}.soloRetryMsg{font-size:17px;font-weight:900;line-height:1.35;margin:14px 0}';document.head.appendChild(s)}
function shell(title,body,buttons){ensureStyles();const old=document.getElementById('soloRankOv');if(old)old.remove();const ov=document.createElement('div');ov.id='soloRankOv';ov.className='soloRankOv';ov.innerHTML='<div class="soloRankCard"><h2>'+title+'</h2>'+body+'<div class="soloRankBtns">'+buttons+'</div><div style="margin-top:10px;font-size:10px;color:#cbd5e1;font-weight:800">Jogo idealizado pelo Prof. Jasson Bruno</div></div>';document.body.appendChild(ov);return ov}
async function complete(game,score,correct,wrong){const p=profile();if(!p||!p.name){location.href='./index.html?cadastro=1';return}score=Math.max(0,Math.round(score||0));correct=Math.max(0,Math.round(correct||0));wrong=Math.max(0,Math.round(wrong||0));if(!sb){shell('🏆 JOGO CONCLUÍDO','<div class="soloRetryMsg">Pontuação: '+score+'</div>','<button class="soloAgain" onclick="location.reload()">🔁 JOGAR NOVAMENTE</button><a class="soloHub" href="./index.html">← JOGOS</a>');return}const row={game:game,player_name:p.name,class_name:p.className,school_name:p.school||'Escola Delfina de Jesus Amorim',device_id:deviceId(),score:score,correct:correct,wrong:wrong,completed:true};try{await sb.from('solo7_game_results').insert(row)}catch(e){}let data=[];try{const res=await sb.from('solo7_leaderboard').select('player_name,class_name,device_id,score,correct,wrong').eq('game',game).order('score',{ascending:false}).order('correct',{ascending:false}).order('wrong',{ascending:true}).limit(20);data=res.data||[]}catch(e){}const me=deviceId(),myIndex=data.findIndex(x=>x.device_id===me),myRank=myIndex>=0?myIndex+1:null;const rows=data.slice(0,10).map((x,i)=>'<div class="soloRankRow '+(x.device_id===me?'me':'')+'"><span>'+(i===0?'🥇':i===1?'🥈':i===2?'🥉':(i+1)+'º')+'</span><span>'+esc(x.player_name)+'<small>Turma '+esc(x.class_name)+'</small></span><span>'+x.score+' pts</span></div>').join('');const title='🏆 RANKING — '+(GAME_NAMES[game]||'JOGO');const meText=myRank?'<div class="soloRankMe">Sua posição: '+myRank+'º • '+score+' pontos</div>':'<div class="soloRankMe">Você fez '+score+' pontos!</div>';shell(title,meText+'<div class="soloRankList">'+(rows||'<div class="soloRetryMsg">Primeiro resultado registrado. Você abriu o ranking!</div>')+'</div>','<button class="soloAgain" onclick="location.reload()">🔁 JOGAR NOVAMENTE</button><a class="soloHub" href="./index.html">← JOGOS</a>')}
function retry(message){shell('💪 TENTE NOVAMENTE','<div class="soloRetryMsg">'+esc(message||'Você ainda não concluiu esta fase. Tente mais uma vez!')+'</div>','<button class="soloAgain" onclick="location.reload()">🔁 TENTAR NOVAMENTE</button><a class="soloHub" href="./index.html">← JOGOS</a>')}
window.SoloRank={complete:complete,retry:retry,profile:profile};
})();