window.GRADE6_DATA={
vocab:[
["mother","mãe"],["father","pai"],["sister","irmã"],["brother","irmão"],["grandmother","avó"],["grandfather","avô"],["aunt","tia"],["uncle","tio"],["cousin","primo / prima"],
["living room","sala de estar"],["bedroom","quarto"],["bathroom","banheiro"],["kitchen","cozinha"],["dining room","sala de jantar"],["laundry room","lavanderia"],["hallway","corredor"],["front yard","área da frente"],["backyard","quintal dos fundos"],["garden","jardim"],["garage","garagem"],["gate","portão"],["roof","telhado"],["wall","parede / muro"],["balcony","varanda"],
["sofa","sofá"],["bed","cama"],["table","mesa"],["chair","cadeira"],["fridge","geladeira"],["stove","fogão"],["sink","pia"],["shower","chuveiro"],["window","janela"],["door","porta"],["desk","escrivaninha"],["lamp","lâmpada / abajur"],["house","casa"],["room","cômodo / quarto"],["family","família"],["home","lar / casa"]
],
words:[
["MOTHER","mãe"],["FATHER","pai"],["SISTER","irmã"],["BROTHER","irmão"],["AUNT","tia"],["UNCLE","tio"],["COUSIN","primo / prima"],["HOUSE","casa"],["ROOM","cômodo"],["HOME","lar"],["BEDROOM","quarto"],["BATHROOM","banheiro"],["KITCHEN","cozinha"],["GARDEN","jardim"],["GARAGE","garagem"],["SOFA","sofá"],["BED","cama"],["TABLE","mesa"],["CHAIR","cadeira"],["FRIDGE","geladeira"],["STOVE","fogão"],["SINK","pia"],["SHOWER","chuveiro"],["WINDOW","janela"],["DOOR","porta"],["BOOK","livro"],["BOX","caixa"],["BUS","ônibus"],["CITY","cidade"],["FAMILY","família"],["BABY","bebê"],["CLASS","turma"],["TOY","brinquedo"],["KEY","chave"],["READ","ler"],["WRITE","escrever"],["PLAY","jogar / brincar"],["STUDY","estudar"],["WATCH","assistir"],["EAT","comer"],["DRINK","beber"],["SLEEP","dormir"],["LISTEN","ouvir"],["DRAW","desenhar"]
],
grammar:[
{t:"There is / There are",q:"Complete: _____ a bed in the bedroom.",o:["There is","There are","Is there","Are there"],a:0,e:"Uma coisa: usamos THERE IS."},
{t:"There is / There are",q:"Complete: _____ two chairs in the kitchen.",o:["There are","There is","Is there","Are there"],a:0,e:"Duas coisas: usamos THERE ARE."},
{t:"There is / There are",q:"Complete: _____ a sofa in the living room.",o:["There is","There are","Are there","There"],a:0,e:"SOFA está no singular."},
{t:"There is / There are",q:"Complete: _____ three windows in the house.",o:["There are","There is","Is there","There"],a:0,e:"THREE WINDOWS está no plural."},
{t:"Plural of Nouns",q:"Pedro escreveu BOOKS como “bookes”. Qual é a correção?",o:["books","bookes","bookies","bookses"],a:0,e:"BOOK recebe apenas -S: BOOKS."},
{t:"Plural of Nouns",q:"Ana escreveu BOX no plural como “boxs”. Qual é a correção?",o:["boxes","boxs","boxies","boxeses"],a:0,e:"BOX termina em X, por isso recebe -ES."},
{t:"Plural of Nouns",q:"João escreveu BUS no plural como “buss”. Qual é a correção?",o:["buses","buss","busies","busseses"],a:0,e:"BUS termina em S e recebe -ES."},
{t:"Plural of Nouns",q:"Lucas escreveu FAMILY no plural como “familys”. Qual é a correção?",o:["families","familys","familyes","familis"],a:0,e:"Consoante + Y: FAMILY → FAMILIES."},
{t:"Plural of Nouns",q:"Carla escreveu CITY no plural como “citys”. Qual é a correção?",o:["cities","citys","cityes","citis"],a:0,e:"Consoante + Y: CITY → CITIES."},
{t:"Plural of Nouns",q:"Bia escreveu BABY no plural como “babys”. Qual é a correção?",o:["babies","babys","babyes","babis"],a:0,e:"Consoante + Y: BABY → BABIES."},
{t:"Plural of Nouns",q:"A forma “windowes” está errada. Qual é o plural correto?",o:["windows","windowes","windowies","windowses"],a:0,e:"WINDOW recebe apenas -S."},
{t:"Plural of Nouns",q:"A forma “toies” está errada. Qual é o plural correto de TOY?",o:["toys","toies","toyes","toyies"],a:0,e:"Vogal + Y: apenas acrescentamos -S."},
{t:"Sentence Check",q:"Corrija: “There are two chair in the kitchen.”",o:["There are two chairs in the kitchen.","There is two chairs in the kitchen.","There are two chair in the kitchen.","There is two chair in the kitchen."],a:0,e:"Depois de TWO, usamos CHAIRS; com plural, THERE ARE."},
{t:"Sentence Check",q:"Corrija: “There is two windows in the bedroom.”",o:["There are two windows in the bedroom.","There is two window in the bedroom.","There are two window in the bedroom.","There is two windows in the bedroom."],a:0,e:"TWO WINDOWS é plural: THERE ARE."},
{t:"House Context",q:"Na cozinha há uma geladeira. Complete: _____ a fridge in the kitchen.",o:["There is","There are","There am","Are there"],a:0,e:"Uma geladeira: THERE IS."},
{t:"House Context",q:"No quarto há duas camas. Complete: _____ two beds in the bedroom.",o:["There are","There is","There am","Is there"],a:0,e:"Duas camas: THERE ARE."},
{t:"Singular or Plural",q:"Complete: There _____ one bathroom in the house.",o:["is","are","am","be"],a:0,e:"ONE BATHROOM é singular."},
{t:"Singular or Plural",q:"Complete: There _____ four chairs in the dining room.",o:["are","is","am","be"],a:0,e:"FOUR CHAIRS é plural."},
{t:"Plural of Nouns",q:"Corrija a expressão: “two boxs”.",o:["two boxes","two boxs","two boxies","two box"],a:0,e:"BOX → BOXES."},
{t:"Plural of Nouns",q:"Corrija a expressão: “three familys”.",o:["three families","three familys","three familyes","three family"],a:0,e:"FAMILY → FAMILIES."}
],
present:[
{t:"Verb to be",q:"Complete: I _____ studying now.",o:["am","is","are","be"],a:0,e:"Com I usamos AM."},
{t:"Verb to be",q:"Complete: She _____ reading a book.",o:["is","am","are","be"],a:0,e:"Com SHE usamos IS."},
{t:"Verb to be",q:"Complete: He _____ playing soccer.",o:["is","am","are","be"],a:0,e:"Com HE usamos IS."},
{t:"Verb to be",q:"Complete: They _____ watching TV.",o:["are","is","am","be"],a:0,e:"Com THEY usamos ARE."},
{t:"Verb to be",q:"Complete: We _____ studying English.",o:["are","is","am","be"],a:0,e:"Com WE usamos ARE."},
{t:"Verb to be",q:"Complete: You _____ listening to music.",o:["are","is","am","be"],a:0,e:"Com YOU usamos ARE."},
{t:"-ING form",q:"Complete: She is _____ a book.",o:["reading","read","reads","reader"],a:0,e:"Present Continuous usa verbo com -ING."},
{t:"-ING form",q:"Complete: They are _____ soccer.",o:["playing","play","plays","played"],a:0,e:"PLAY → PLAYING."},
{t:"-ING form",q:"Complete: He is _____ TV.",o:["watching","watch","watches","watched"],a:0,e:"WATCH → WATCHING."},
{t:"-ING form",q:"Complete: We are _____ English.",o:["studying","study","studies","studied"],a:0,e:"STUDY → STUDYING."},
{t:"Complete Structure",q:"Qual frase está completa e correta?",o:["She is cooking in the kitchen.","She cooking in the kitchen.","She is cook in the kitchen.","She are cooking in the kitchen."],a:0,e:"Precisamos de SHE + IS + COOKING."},
{t:"Complete Structure",q:"Qual frase está completa e correta?",o:["They are playing in the garden.","They playing in the garden.","They is playing in the garden.","They are play in the garden."],a:0,e:"Precisamos de THEY + ARE + PLAYING."},
{t:"Complete Structure",q:"Qual frase está completa e correta?",o:["I am studying now.","I studying now.","I is studying now.","I am study now."],a:0,e:"I + AM + STUDYING."},
{t:"Error Hunt",q:"O que falta em “She cooking now”?",o:["is","am","are","-s"],a:0,e:"Falta o verbo to be IS."},
{t:"Error Hunt",q:"O que falta em “They playing soccer”?",o:["are","is","am","-s"],a:0,e:"Falta o verbo to be ARE."},
{t:"Error Hunt",q:"Em “He is play soccer”, o que deve mudar?",o:["play → playing","is → are","He → They","soccer → soccers"],a:0,e:"O verbo principal precisa de -ING."},
{t:"Error Hunt",q:"Em “I is studying”, qual é a correção?",o:["I am studying.","I are studying.","I studying.","I is study."],a:0,e:"Com I usamos AM."},
{t:"Sentence Builder",q:"Escolha a ordem correta.",o:["She + is + reading.","She + reading + is.","Is + she + reading.","She + read + is."],a:0,e:"Afirmativa: sujeito + am/is/are + verbo-ing."},
{t:"Context",q:"Ana está cozinhando agora. Qual frase está correta?",o:["Ana is cooking now.","Ana cooking now.","Ana are cooking now.","Ana is cook now."],a:0,e:"Ana = she: IS + COOKING."},
{t:"Structure",q:"Qual estrutura representa o Present Continuous afirmativo?",o:["subject + am/is/are + verb-ing","subject + verb","am/is/are + subject + verb","subject + do/does + verb"],a:0,e:"Sujeito + am/is/are + verbo com -ing."}
],
genitive:[
{t:"Family",q:"“mother” significa:",o:["mãe","pai","irmã","tia"],a:0,e:"MOTHER = mãe."},
{t:"Family",q:"“brother” significa:",o:["irmão","primo","pai","avô"],a:0,e:"BROTHER = irmão."},
{t:"Family",q:"“aunt” significa:",o:["tia","irmã","avó","prima"],a:0,e:"AUNT = tia."},
{t:"Form",q:"Para dizer “a mãe de Ana”, qual está correta?",o:["Ana's mother","mother Ana's","Ana mother","Anas mother"],a:0,e:"Ana's mother = a mãe de Ana."},
{t:"Form",q:"Para dizer “o pai de Pedro”, qual está correta?",o:["Pedro's father","father's Pedro","Pedro father","Pedros father"],a:0,e:"Pedro's father = o pai de Pedro."},
{t:"Form",q:"Para dizer “a irmã de Julia”, qual está correta?",o:["Julia's sister","sister Julia's","Julia sister","Julias sister"],a:0,e:"Julia's sister = a irmã de Julia."},
{t:"Form",q:"Onde colocamos o 's no caso genitivo estudado?",o:["Depois do nome da pessoa","Antes do nome da pessoa","Depois do familiar","No final da frase"],a:0,e:"O 's vem depois do nome da pessoa."},
{t:"Build",q:"Complete: a mãe de Ben = Ben's _____.",o:["mother","father","sister","aunt"],a:0,e:"Ben's mother."},
{t:"Build",q:"Complete: o irmão de Sofia = Sofia's _____.",o:["brother","mother","uncle","cousin"],a:0,e:"Sofia's brother."},
{t:"Build",q:"Complete: a tia de Carla = Carla's _____.",o:["aunt","uncle","sister","mother"],a:0,e:"Carla's aunt."},
{t:"Relation",q:"“Laura's brother” significa:",o:["o irmão de Laura","a irmã de Laura","o pai de Laura","Laura é irmã"],a:0,e:"Laura's brother = o irmão de Laura."},
{t:"Relation",q:"“Pedro's mother” significa:",o:["a mãe de Pedro","o pai de Pedro","a irmã de Pedro","Pedro é mãe"],a:0,e:"Pedro's mother = a mãe de Pedro."},
{t:"Relation",q:"“Julia's grandmother” significa:",o:["a avó de Julia","o avô de Julia","a tia de Julia","a mãe de Julia"],a:0,e:"Julia's grandmother = a avó de Julia."},
{t:"Relation",q:"Lucas is Ana's brother. Quem é Lucas?",o:["o irmão de Ana","o pai de Ana","o primo de Ana","o avô de Ana"],a:0,e:"Lucas é o irmão de Ana."},
{t:"Relation",q:"Bia is Tom's sister. Quem é Bia?",o:["a irmã de Tom","a mãe de Tom","a tia de Tom","a prima de Tom"],a:0,e:"Bia é a irmã de Tom."},
{t:"Review",q:"Qual expressão está escrita corretamente?",o:["Rafael's father","Rafael father","Rafaels father","father Rafael's"],a:0,e:"Rafael's father está correta."},
{t:"Review",q:"Qual expressão está escrita corretamente?",o:["Clara's uncle","Clara uncle","Claras uncle","uncle's Clara"],a:0,e:"Clara's uncle está correta."},
{t:"Review",q:"Escolha a tradução correta de “Marcos's cousin”.",o:["o primo/a prima de Marcos","o irmão de Marcos","o tio de Marcos","o pai de Marcos"],a:0,e:"Marcos's cousin."},
{t:"Review",q:"Complete: Ana's _____ = o pai de Ana.",o:["father","mother","brother","uncle"],a:0,e:"Ana's father."},
{t:"Review",q:"Complete: Sofia's _____ = a avó de Sofia.",o:["grandmother","grandfather","mother","aunt"],a:0,e:"Sofia's grandmother."}
]
};